export const fonts = {
    PlusJakartaSans: "PlusJakartaSans",
    PlusJakartaSansExtraLight: "PlusJakartaSansExtraLight",
    PlusJakartaSansLight: "PlusJakartaSansLight",
    PlusJakartaSansMedium: "PlusJakartaSansMedium",
    PlusJakartaSansSemiBold: "PlusJakartaSansSemiBold",
    PlusJakartaSansBold: "PlusJakartaSansBold",
    PlusJakartaSansExtraBold: "PlusJakartaSansExtraBold",
    Outfit: "PlusJakartaSans",
    OutfitExtraLight: "PlusJakartaSansExtraLight",
    OutfitLight: "PlusJakartaSansLight",
    OutfitMedium: "PlusJakartaSansMedium",
    OutfitSemiBold: "PlusJakartaSansSemiBold",
    OutfitBold: "PlusJakartaSansBold",
    OutfitExtraBold: "PlusJakartaSansExtraBold",
}