/**
 * seedProfiles.js
 *
 * Create 20 dummy profiles (mostly African) with full data.
 * Some profiles are pre-matched with each other.
 *
 * Usage:
 *   cd backend && node src/seeders/seedProfiles.js
 *
 * All users share the password: Test1234!
 */

require("dotenv").config();
const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const User = require("../models/User");
const Match = require("../models/Match");

// ── DB connection ────────────────────────────────────────────────────────────
const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("✅ MongoDB Connected");
  } catch (err) {
    console.error("❌ MongoDB connection error:", err);
    process.exit(1);
  }
};

// ── Shared password ──────────────────────────────────────────────────────────
const SHARED_PASSWORD = "Test1234!";

// ── Placeholder images (use randomuser.me or UI Faces style URLs) ────────────
const malePhotos = [
  "https://randomuser.me/api/portraits/men/32.jpg",
  "https://randomuser.me/api/portraits/men/45.jpg",
  "https://randomuser.me/api/portraits/men/67.jpg",
];
const femalePhotos = [
  "https://randomuser.me/api/portraits/women/44.jpg",
  "https://randomuser.me/api/portraits/women/68.jpg",
  "https://randomuser.me/api/portraits/women/21.jpg",
];

const pickPhotos = (gender) => {
  const pool = gender === "Male" ? malePhotos : femalePhotos;
  return pool.map((url, i) => ({ url, publicId: `seed_${Date.now()}_${i}`, order: i }));
};

// ── Profile data ─────────────────────────────────────────────────────────────
const profiles = [
  // ──────────── 1. Adaeze Okafor ────────────
  {
    firstName: "Adaeze",
    lastName: "Okafor",
    email: "adaeze.okafor@test.com",
    gender: "Female",
    age: 25,
    dateOfBirth: new Date("2001-03-15"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Lover of jollof rice, sunsets and deep conversations. Lagos girl with a London heart 💛",
    tagline: "Soft life enthusiast 🌸",
    occupation: "Software Developer",
    education: "Bachelors Degree",
    school: "University of Lagos",
    height: 165,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Igbo", "Yoruba"],
    interests: ["Travel", "Cooking", "Music", "Photography", "Fashion"],
    personalities: ["Creative", "Ambitious", "Outgoing"],
    favoriteMusic: ["Afrobeats", "R&B", "Pop"],
    favoriteVideos: ["Documentaries", "Cooking Shows", "Travel Vlogs"],
    funActivities: ["Hiking", "Cooking", "Dancing"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Sometimes",
    pets: "I want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Thoughtful",
    loveLanguage: "Quality Time",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [3.3792, 6.5244], city: "Lagos", state: "Lagos", country: "Nigeria" },
    questions: [
      { question: "A perfect Sunday looks like…", answer: "Brunch, a good Nollywood movie, and a long phonecall with my mum." },
      { question: "I'm looking for someone who…", answer: "Knows how to laugh at themselves and isn't afraid of commitment." },
    ],
  },

  // ──────────── 2. Chidi Eze ────────────
  {
    firstName: "Chidi",
    lastName: "Eze",
    email: "chidi.eze@test.com",
    gender: "Male",
    age: 28,
    dateOfBirth: new Date("1998-07-22"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Tech bro by day, worship leader by Sunday. Looking for my Proverbs 31 🙏🏾",
    tagline: "God first, code second 💻",
    occupation: "Software Developer",
    education: "Masters Degree",
    school: "Covenant University",
    height: 183,
    bloodGroup: "A+",
    genotype: "AS",
    languages: ["English", "Igbo"],
    interests: ["Music", "Fitness", "Reading", "Volunteering", "Gaming"],
    personalities: ["Ambitious", "Passionate", "Intellectual"],
    favoriteMusic: ["Gospel", "Afrobeats", "Jazz"],
    favoriteVideos: ["Documentaries", "Tech Reviews", "Podcasts"],
    funActivities: ["Gym", "Hiking", "Board Games"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Daily",
    pets: "I don't want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Direct",
    loveLanguage: "Words of Affirmation",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [3.3792, 6.5244], city: "Lagos", state: "Lagos", country: "Nigeria" },
    questions: [
      { question: "My love language is…", answer: "Words of affirmation — tell me you're proud of me and I'm yours forever." },
      { question: "A relationship deal-breaker for me is…", answer: "Dishonesty. I'd rather hear a hard truth than a sweet lie." },
    ],
  },

  // ──────────── 3. Amina Bello ────────────
  {
    firstName: "Amina",
    lastName: "Bello",
    email: "amina.bello@test.com",
    gender: "Female",
    age: 24,
    dateOfBirth: new Date("2002-01-10"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Muslim",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Kano girl in Abuja 🌙 I love henna nights, good food, and meaningful conversations.",
    tagline: "Deen over dunya ✨",
    occupation: "Doctor",
    education: "Bachelors Degree",
    school: "Ahmadu Bello University",
    height: 160,
    bloodGroup: "B+",
    genotype: "AA",
    languages: ["English", "Hausa", "Arabic"],
    interests: ["Reading", "Cooking", "Volunteering", "Fashion", "Art"],
    personalities: ["Easygoing", "Romantic", "Creative"],
    favoriteMusic: ["Nasheed", "Classical", "World Music"],
    favoriteVideos: ["Documentaries", "Cooking Shows", "Podcasts"],
    funActivities: ["Cooking", "Reading", "Yoga"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Sometimes",
    pets: "Prefer not to say",
    children: "I want kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Thoughtful",
    loveLanguage: "Acts of Service",
    financialStyle: "Balanced",
    location: { type: "Point", coordinates: [7.4951, 9.0579], city: "Abuja", state: "FCT", country: "Nigeria" },
    questions: [
      { question: "The key to my heart is…", answer: "Consistency, respect, and someone who fears Allah." },
      { question: "On a Friday evening you'll find me…", answer: "After Jumu'ah, I'm either cooking or binge-watching Korean dramas." },
    ],
  },

  // ──────────── 4. Kwame Asante ────────────
  {
    firstName: "Kwame",
    lastName: "Asante",
    email: "kwame.asante@test.com",
    gender: "Male",
    age: 30,
    dateOfBirth: new Date("1996-04-06"),
    nationality: "Ghanaian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Accra boy making moves. I believe in good vibes, groundnut soup and genuine love.",
    tagline: "Highlife & chill 🎶",
    occupation: "Entrepreneur",
    education: "Bachelors Degree",
    school: "University of Ghana",
    height: 178,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Twi"],
    interests: ["Music", "Travel", "Fitness", "Cooking", "Sports"],
    personalities: ["Adventurous", "Funny", "Outgoing"],
    favoriteMusic: ["Afrobeats", "Highlife", "Hip Hop"],
    favoriteVideos: ["Sports", "Documentaries", "Comedy"],
    funActivities: ["Dancing", "Beach", "Gym"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Often",
    pets: "I have pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Balanced",
    loveLanguage: "Physical Touch",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [-0.187, 5.6037], city: "Accra", state: "Greater Accra", country: "Ghana" },
    questions: [
      { question: "My ideal date is…", answer: "Street food tour in Osu, then a walk on Labadi Beach at sunset." },
      { question: "Something I'm passionate about…", answer: "Building African businesses that solve African problems." },
    ],
  },

  // ──────────── 5. Fatou Diallo ────────────
  {
    firstName: "Fatou",
    lastName: "Diallo",
    email: "fatou.diallo@test.com",
    gender: "Female",
    age: 26,
    dateOfBirth: new Date("2000-08-20"),
    nationality: "Senegalese",
    ethnicity: "African",
    religion: "Muslim",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Dakar → Paris → Lagos. Multilingual creative who believes love transcends borders 🌍",
    tagline: "Teranga spirit 🤍",
    occupation: "Marketing Manager",
    education: "Masters Degree",
    school: "Université Cheikh Anta Diop",
    height: 170,
    bloodGroup: "A+",
    genotype: "AA",
    languages: ["French", "Wolof", "English"],
    interests: ["Fashion", "Travel", "Art", "Photography", "Dancing"],
    personalities: ["Creative", "Outgoing", "Passionate"],
    favoriteMusic: ["Afrobeats", "R&B", "French Pop"],
    favoriteVideos: ["Fashion", "Travel Vlogs", "Documentaries"],
    funActivities: ["Dancing", "Shopping", "Beach"],
    lookingFor: "A Committed relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Sometimes",
    pets: "I want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Emotional",
    loveLanguage: "Quality Time",
    financialStyle: "Balanced",
    location: { type: "Point", coordinates: [-17.4677, 14.7167], city: "Dakar", state: "Dakar", country: "Senegal" },
    questions: [
      { question: "A fun fact about me…", answer: "I speak 4 languages but I still can't say no to thieboudienne 😂" },
      { question: "My love language is…", answer: "Quality time — put your phone away and look me in the eyes." },
    ],
  },

  // ──────────── 6. Obinna Nwosu ────────────
  {
    firstName: "Obinna",
    lastName: "Nwosu",
    email: "obinna.nwosu@test.com",
    gender: "Male",
    age: 27,
    dateOfBirth: new Date("1999-05-12"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Occasionally religious",
    religionImportance: "Is quite important",
    bio: "From Port Harcourt with love. I write code, cook rice, and tell terrible jokes 😄",
    tagline: "PH boy, Lagos hustle 🚀",
    occupation: "Data Scientist",
    education: "Masters Degree",
    school: "University of Port Harcourt",
    height: 180,
    bloodGroup: "O-",
    genotype: "AA",
    languages: ["English", "Igbo", "Pidgin"],
    interests: ["Gaming", "Cooking", "Music", "Fitness", "Movies"],
    personalities: ["Funny", "Intellectual", "Easygoing"],
    favoriteMusic: ["Afrobeats", "Hip Hop", "R&B"],
    favoriteVideos: ["Tech Reviews", "Comedy", "Gaming"],
    funActivities: ["Gaming", "Cooking", "Gym"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Often",
    pets: "I want pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Direct",
    loveLanguage: "Physical Touch",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [3.3792, 6.5244], city: "Lagos", state: "Lagos", country: "Nigeria" },
    questions: [
      { question: "I geek out on…", answer: "Machine learning models and the perfect jollof rice recipe 🍚" },
      { question: "We'd get along if…", answer: "You can handle my sense of humour and love a good food adventure." },
    ],
  },

  // ──────────── 7. Zanele Dlamini ────────────
  {
    firstName: "Zanele",
    lastName: "Dlamini",
    email: "zanele.dlamini@test.com",
    gender: "Female",
    age: 27,
    dateOfBirth: new Date("1999-11-08"),
    nationality: "South African",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Spiritual but not religious",
    religionImportance: "It doesn't matter to me at all",
    bio: "Joburg creative director who loves braai weekends and mountain hikes 🏔️",
    tagline: "Ubuntu vibes only 🤎",
    occupation: "Graphic Designer",
    education: "Bachelors Degree",
    school: "University of Cape Town",
    height: 168,
    bloodGroup: "A+",
    genotype: "AA",
    languages: ["English", "Zulu", "Afrikaans"],
    interests: ["Art", "Hiking", "Photography", "Music", "Travel"],
    personalities: ["Creative", "Adventurous", "Passionate"],
    favoriteMusic: ["Amapiano", "R&B", "Jazz"],
    favoriteVideos: ["Documentaries", "Art & Design", "Travel Vlogs"],
    funActivities: ["Hiking", "Photography", "Beach"],
    lookingFor: "A Committed relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Often",
    pets: "I have pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Balanced",
    loveLanguage: "Receiving Gifts",
    financialStyle: "Balanced",
    location: { type: "Point", coordinates: [28.0473, -26.2041], city: "Johannesburg", state: "Gauteng", country: "South Africa" },
    questions: [
      { question: "On weekends you'll find me…", answer: "Hiking Table Mountain or exploring Maboneng street art." },
      { question: "My non-negotiable is…", answer: "Emotional intelligence. Know yourself before you love me." },
    ],
  },

  // ──────────── 8. Emeka Obi ────────────
  {
    firstName: "Emeka",
    lastName: "Obi",
    email: "emeka.obi@test.com",
    gender: "Male",
    age: 31,
    dateOfBirth: new Date("1995-02-14"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Valentine baby 💘 Doctor by profession, worship leader by calling. Abuja based.",
    tagline: "Faith + Purpose 🙏🏾",
    occupation: "Doctor",
    education: "Masters Degree",
    school: "University of Nigeria, Nsukka",
    height: 185,
    bloodGroup: "B+",
    genotype: "AA",
    languages: ["English", "Igbo"],
    interests: ["Reading", "Music", "Volunteering", "Fitness", "Travel"],
    personalities: ["Passionate", "Romantic", "Intellectual"],
    favoriteMusic: ["Gospel", "Classical", "Afrobeats"],
    favoriteVideos: ["Documentaries", "Medical", "Podcasts"],
    funActivities: ["Volunteering", "Gym", "Hiking"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Daily",
    pets: "I don't want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Thoughtful",
    loveLanguage: "Acts of Service",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [7.4951, 9.0579], city: "Abuja", state: "FCT", country: "Nigeria" },
    questions: [
      { question: "I'm looking for someone who…", answer: "Loves God genuinely and isn't just performing religion." },
      { question: "A perfect Sunday looks like…", answer: "Church in the morning, hospital rounds, and a quiet dinner together." },
    ],
  },

  // ──────────── 9. Nia Mensah ────────────
  {
    firstName: "Nia",
    lastName: "Mensah",
    email: "nia.mensah@test.com",
    gender: "Female",
    age: 23,
    dateOfBirth: new Date("2003-06-30"),
    nationality: "Ghanaian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Accra babe studying law. I'll argue with you for fun — and win 😏",
    tagline: "Future attorney ⚖️",
    occupation: "Student",
    education: "Bachelors Degree",
    school: "University of Ghana",
    height: 163,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Twi", "Ga"],
    interests: ["Reading", "Dancing", "Music", "Fashion", "Movies"],
    personalities: ["Intellectual", "Funny", "Ambitious"],
    favoriteMusic: ["Afrobeats", "Highlife", "Pop"],
    favoriteVideos: ["True Crime", "Documentaries", "Comedy"],
    funActivities: ["Dancing", "Beach", "Board Games"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Rarely",
    exercise: "Sometimes",
    pets: "I want pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Direct",
    loveLanguage: "Words of Affirmation",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [-0.187, 5.6037], city: "Accra", state: "Greater Accra", country: "Ghana" },
    questions: [
      { question: "A fun fact about me…", answer: "I once won a debate competition in my sleep — okay maybe not, but close!" },
      { question: "We'd get along if…", answer: "You love banter, kelewele, and aren't intimidated by a smart woman." },
    ],
  },

  // ──────────── 10. Tunde Adeyemi ────────────
  {
    firstName: "Tunde",
    lastName: "Adeyemi",
    email: "tunde.adeyemi@test.com",
    gender: "Male",
    age: 29,
    dateOfBirth: new Date("1997-09-03"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Muslim",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Yoruba boy with a big heart. Finance professional who can also make a mean amala 🍛",
    tagline: "Numbers + Nollywood 🎬",
    occupation: "Accountant",
    education: "Masters Degree",
    school: "University of Ibadan",
    height: 176,
    bloodGroup: "A+",
    genotype: "AS",
    languages: ["English", "Yoruba", "Arabic"],
    interests: ["Sports", "Cooking", "Movies", "Travel", "Reading"],
    personalities: ["Easygoing", "Funny", "Romantic"],
    favoriteMusic: ["Afrobeats", "Fuji", "R&B"],
    favoriteVideos: ["Sports", "Nollywood", "Documentaries"],
    funActivities: ["Cooking", "Sports", "Cinema"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Often",
    pets: "I don't want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Balanced",
    loveLanguage: "Acts of Service",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [3.3792, 6.5244], city: "Lagos", state: "Lagos", country: "Nigeria" },
    questions: [
      { question: "My ideal date is…", answer: "A nice Owambe party where we eat, dance, and spray money together 😄" },
      { question: "I'm looking for someone who…", answer: "Values family, has ambition, and can handle Yoruba mother-in-laws." },
    ],
  },

  // ──────────── 11. Chiamaka Nnadi ────────────
  {
    firstName: "Chiamaka",
    lastName: "Nnadi",
    email: "chiamaka.nnadi@test.com",
    gender: "Female",
    age: 26,
    dateOfBirth: new Date("2000-12-25"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Christmas baby 🎄 Pharmacist who sings in the choir. Looking for my bestfriend + soulmate.",
    tagline: "Grace upon grace 🕊️",
    occupation: "Pharmacist",
    education: "Bachelors Degree",
    school: "University of Benin",
    height: 162,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Igbo"],
    interests: ["Music", "Reading", "Cooking", "Volunteering", "Yoga"],
    personalities: ["Romantic", "Easygoing", "Creative"],
    favoriteMusic: ["Gospel", "R&B", "Classical"],
    favoriteVideos: ["Cooking Shows", "Podcasts", "Faith"],
    funActivities: ["Cooking", "Yoga", "Volunteering"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Sometimes",
    pets: "I want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Emotional",
    loveLanguage: "Words of Affirmation",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [3.3792, 6.5244], city: "Lagos", state: "Lagos", country: "Nigeria" },
    questions: [
      { question: "The key to my heart is…", answer: "Be consistent, be kind, and know how to make me laugh in church 😂" },
      { question: "My love language is…", answer: "Tell me sweet things and mean every word." },
    ],
  },

  // ──────────── 12. Sekou Traore ────────────
  {
    firstName: "Sekou",
    lastName: "Traore",
    email: "sekou.traore@test.com",
    gender: "Male",
    age: 32,
    dateOfBirth: new Date("1994-03-28"),
    nationality: "Malian",
    ethnicity: "African",
    religion: "Muslim",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Bamako raised, Dubai based. Engineer building bridges — literally and figuratively 🌉",
    tagline: "Bismillah always 🤲🏾",
    occupation: "Engineer",
    education: "Masters Degree",
    school: "University of Bamako",
    height: 188,
    bloodGroup: "B+",
    genotype: "AA",
    languages: ["French", "Bambara", "English", "Arabic"],
    interests: ["Travel", "Fitness", "Reading", "Sports", "Volunteering"],
    personalities: ["Ambitious", "Passionate", "Intellectual"],
    favoriteMusic: ["Nasheed", "Afrobeats", "World Music"],
    favoriteVideos: ["Documentaries", "Engineering", "Sports"],
    funActivities: ["Gym", "Hiking", "Sports"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Daily",
    pets: "I don't want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Direct",
    loveLanguage: "Quality Time",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [-8.0029, 12.6392], city: "Bamako", state: "Bamako", country: "Mali" },
    questions: [
      { question: "I'm passionate about…", answer: "Infrastructure development in Africa. We deserve world-class roads." },
      { question: "I'm looking for someone who…", answer: "Shares my faith, respects family values, and has her own dreams." },
    ],
  },

  // ──────────── 13. Aisha Musa ────────────
  {
    firstName: "Aisha",
    lastName: "Musa",
    email: "aisha.musa@test.com",
    gender: "Female",
    age: 25,
    dateOfBirth: new Date("2001-06-15"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Muslim",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Hijabi queen with a PhD dream 👩🏾‍🎓 Kaduna girl, Abuja living. Tea > Coffee.",
    tagline: "Modesty is beauty 🌙",
    occupation: "Researcher",
    education: "Masters Degree",
    school: "Bayero University Kano",
    height: 158,
    bloodGroup: "A-",
    genotype: "AA",
    languages: ["English", "Hausa", "Arabic", "French"],
    interests: ["Reading", "Writing", "Volunteering", "Art", "Cooking"],
    personalities: ["Intellectual", "Creative", "Easygoing"],
    favoriteMusic: ["Nasheed", "Classical", "World Music"],
    favoriteVideos: ["Documentaries", "Educational", "Podcasts"],
    funActivities: ["Reading", "Cooking", "Board Games"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Rarely",
    pets: "Prefer not to say",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Thoughtful",
    loveLanguage: "Acts of Service",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [7.4951, 9.0579], city: "Abuja", state: "FCT", country: "Nigeria" },
    questions: [
      { question: "The way to my heart is…", answer: "Through my mind first. Stimulate my intellect and I'm all yours." },
      { question: "A perfect evening looks like…", answer: "Tea, a great book, and iftar with someone special during Ramadan." },
    ],
  },

  // ──────────── 14. Daniel Kipchoge ────────────
  {
    firstName: "Daniel",
    lastName: "Kipchoge",
    email: "daniel.kipchoge@test.com",
    gender: "Male",
    age: 26,
    dateOfBirth: new Date("2000-01-05"),
    nationality: "Kenyan",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Nairobi based product designer. Marathon runner (not as fast as the other Kipchoge 😅).",
    tagline: "Design + Discipline 🎯",
    occupation: "Graphic Designer",
    education: "Bachelors Degree",
    school: "University of Nairobi",
    height: 175,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Swahili"],
    interests: ["Fitness", "Art", "Photography", "Travel", "Coffee"],
    personalities: ["Adventurous", "Creative", "Ambitious"],
    favoriteMusic: ["Afrobeats", "Gengetone", "Pop"],
    favoriteVideos: ["Design", "Sports", "Travel Vlogs"],
    funActivities: ["Running", "Photography", "Hiking"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Daily",
    pets: "I want pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Balanced",
    loveLanguage: "Quality Time",
    financialStyle: "Balanced",
    location: { type: "Point", coordinates: [36.8219, -1.2921], city: "Nairobi", state: "Nairobi", country: "Kenya" },
    questions: [
      { question: "A fun fact about me…", answer: "I've run 3 marathons and cried at the finish line of every single one 🥹" },
      { question: "My ideal date is…", answer: "Coffee at a rooftop cafe in Westlands, then a sunset run at Karura Forest." },
    ],
  },

  // ──────────── 15. Ngozi Achebe ────────────
  {
    firstName: "Ngozi",
    lastName: "Achebe",
    email: "ngozi.achebe@test.com",
    gender: "Female",
    age: 28,
    dateOfBirth: new Date("1998-04-18"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Banker by day, foodie by night. Enugu roots, Lagos life. I love pepper soup weather 🌧️",
    tagline: "Work hard, eat well 🍜",
    occupation: "Accountant",
    education: "Masters Degree",
    school: "University of Nigeria, Nsukka",
    height: 167,
    bloodGroup: "B+",
    genotype: "AS",
    languages: ["English", "Igbo"],
    interests: ["Cooking", "Travel", "Fashion", "Movies", "Wine"],
    personalities: ["Ambitious", "Outgoing", "Romantic"],
    favoriteMusic: ["Afrobeats", "R&B", "Pop"],
    favoriteVideos: ["Nollywood", "Cooking Shows", "Comedy"],
    funActivities: ["Cooking", "Dancing", "Shopping"],
    lookingFor: "A Committed relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Sometimes",
    pets: "I want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Emotional",
    loveLanguage: "Receiving Gifts",
    financialStyle: "Balanced",
    location: { type: "Point", coordinates: [3.3792, 6.5244], city: "Lagos", state: "Lagos", country: "Nigeria" },
    questions: [
      { question: "The way to my heart is…", answer: "Through my stomach. Cook for me and I'll love you forever 😍" },
      { question: "A relationship deal-breaker is…", answer: "Stinginess. Not about money — stingy with time, love, and effort." },
    ],
  },

  // ──────────── 16. Yaw Boateng ────────────
  {
    firstName: "Yaw",
    lastName: "Boateng",
    email: "yaw.boateng@test.com",
    gender: "Male",
    age: 25,
    dateOfBirth: new Date("2001-07-14"),
    nationality: "Ghanaian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Occasionally religious",
    religionImportance: "Is quite important",
    bio: "Kumasi boy in London 🇬🇧 Studying finance, cooking jollof, and looking for my person.",
    tagline: "Ghana boy abroad 🌍",
    occupation: "Student",
    education: "Masters Degree",
    school: "London School of Economics",
    height: 181,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Twi"],
    interests: ["Sports", "Music", "Gaming", "Cooking", "Travel"],
    personalities: ["Funny", "Easygoing", "Adventurous"],
    favoriteMusic: ["Afrobeats", "Drill", "Highlife"],
    favoriteVideos: ["Sports", "Comedy", "Gaming"],
    funActivities: ["Sports", "Gaming", "Cooking"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Often",
    pets: "I want pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Direct",
    loveLanguage: "Physical Touch",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [-0.1278, 51.5074], city: "London", state: "England", country: "United Kingdom" },
    questions: [
      { question: "We'd get along if…", answer: "You can handle Twi being spoken at family gatherings 😂" },
      { question: "My ideal weekend is…", answer: "Arsenal match on Saturday, Sunday lunch with the fam." },
    ],
  },

  // ──────────── 17. Thandiwe Moyo ────────────
  {
    firstName: "Thandiwe",
    lastName: "Moyo",
    email: "thandiwe.moyo@test.com",
    gender: "Female",
    age: 29,
    dateOfBirth: new Date("1997-10-02"),
    nationality: "Zimbabwean",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Spiritual but not religious",
    religionImportance: "Is quite important",
    bio: "Harare → Cape Town. Lawyer, wine lover, and firm believer in second chapters 📖",
    tagline: "Elegant chaos ✨",
    occupation: "Lawyer",
    education: "Masters Degree",
    school: "University of Cape Town",
    height: 171,
    bloodGroup: "A+",
    genotype: "AA",
    languages: ["English", "Shona", "Ndebele"],
    interests: ["Reading", "Wine", "Travel", "Art", "Hiking"],
    personalities: ["Intellectual", "Ambitious", "Passionate"],
    favoriteMusic: ["Jazz", "R&B", "Amapiano"],
    favoriteVideos: ["True Crime", "Documentaries", "Podcasts"],
    funActivities: ["Hiking", "Wine Tasting", "Reading"],
    lookingFor: "A Committed relationship",
    relationshipType: "Divorced",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Often",
    pets: "I have pets",
    children: "I have kids",
    willRelocateForMarriage: "Probably not",
    communicationStyle: "Thoughtful",
    loveLanguage: "Quality Time",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [18.4241, -33.9249], city: "Cape Town", state: "Western Cape", country: "South Africa" },
    questions: [
      { question: "Something I've learned about love…", answer: "It's not about finding someone perfect — it's about finding someone honest." },
      { question: "A non-negotiable for me is…", answer: "Maturity. I've done the games; I want something real now." },
    ],
  },

  // ──────────── 18. Ibrahim Abdullahi ────────────
  {
    firstName: "Ibrahim",
    lastName: "Abdullahi",
    email: "ibrahim.abdullahi@test.com",
    gender: "Male",
    age: 33,
    dateOfBirth: new Date("1993-08-08"),
    nationality: "Nigerian",
    ethnicity: "African",
    religion: "Muslim",
    religionPractice: "Very religious",
    religionImportance: "Is very important",
    bio: "Kano to Abuja. Architect designing mosques and homes 🕌 Looking for my better half.",
    tagline: "Build with me 🏗️",
    occupation: "Architect",
    education: "Masters Degree",
    school: "Ahmadu Bello University",
    height: 182,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Hausa", "Arabic"],
    interests: ["Art", "Reading", "Travel", "Photography", "Sports"],
    personalities: ["Creative", "Intellectual", "Romantic"],
    favoriteMusic: ["Nasheed", "Classical", "World Music"],
    favoriteVideos: ["Architecture", "Documentaries", "Travel Vlogs"],
    funActivities: ["Photography", "Hiking", "Sports"],
    lookingFor: "Marriage Focused",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "No, I don't drink",
    exercise: "Often",
    pets: "I don't want pets",
    children: "I want kids",
    willRelocateForMarriage: "Yes, definitely",
    communicationStyle: "Thoughtful",
    loveLanguage: "Acts of Service",
    financialStyle: "Investor",
    location: { type: "Point", coordinates: [7.4951, 9.0579], city: "Abuja", state: "FCT", country: "Nigeria" },
    questions: [
      { question: "I'm passionate about…", answer: "Designing spaces that tell stories. Every building should have a soul." },
      { question: "My ideal partner…", answer: "Is God-fearing, cultured, and isn't afraid to dream big with me." },
    ],
  },

  // ──────────── 19. Efua Owusu ────────────
  {
    firstName: "Efua",
    lastName: "Owusu",
    email: "efua.owusu@test.com",
    gender: "Female",
    age: 24,
    dateOfBirth: new Date("2002-05-05"),
    nationality: "Ghanaian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Born on a Friday 🇬🇭 Nurse by profession, dancer by passion. Accra is home.",
    tagline: "Healing hearts 💕",
    occupation: "Nurse",
    education: "Bachelors Degree",
    school: "University of Ghana",
    height: 164,
    bloodGroup: "O+",
    genotype: "AA",
    languages: ["English", "Twi", "Fante"],
    interests: ["Dancing", "Music", "Cooking", "Movies", "Fitness"],
    personalities: ["Outgoing", "Easygoing", "Romantic"],
    favoriteMusic: ["Afrobeats", "Highlife", "R&B"],
    favoriteVideos: ["Comedy", "Cooking Shows", "Documentaries"],
    funActivities: ["Dancing", "Beach", "Cooking"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Rarely",
    exercise: "Sometimes",
    pets: "I want pets",
    children: "I want kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Emotional",
    loveLanguage: "Physical Touch",
    financialStyle: "Saver",
    location: { type: "Point", coordinates: [-0.187, 5.6037], city: "Accra", state: "Greater Accra", country: "Ghana" },
    questions: [
      { question: "A perfect date is…", answer: "Dancing at a beach bar in Labadi with good music and great company 💃🏾" },
      { question: "We'd get along if…", answer: "You can dance. I don't care if you're bad at it — just try!" },
    ],
  },

  // ──────────── 20. Kofi Mensah ────────────
  {
    firstName: "Kofi",
    lastName: "Mensah",
    email: "kofi.mensah@test.com",
    gender: "Male",
    age: 28,
    dateOfBirth: new Date("1998-10-22"),
    nationality: "Ghanaian",
    ethnicity: "African",
    religion: "Christian",
    religionPractice: "Moderately religious",
    religionImportance: "Is quite important",
    bio: "Born on Friday, living for the weekends 🇬🇭 DJ + software engineer. Accra nights, Lagos vibes.",
    tagline: "Code by day, decks by night 🎧",
    occupation: "Software Developer",
    education: "Bachelors Degree",
    school: "KNUST",
    height: 179,
    bloodGroup: "B+",
    genotype: "AA",
    languages: ["English", "Twi", "Pidgin"],
    interests: ["Music", "Gaming", "Travel", "Fitness", "Photography"],
    personalities: ["Funny", "Creative", "Adventurous"],
    favoriteMusic: ["Afrobeats", "Amapiano", "Hip Hop"],
    favoriteVideos: ["Music", "Tech Reviews", "Comedy"],
    funActivities: ["DJ", "Beach", "Gaming"],
    lookingFor: "Long term relationship",
    relationshipType: "Never married",
    smoking: "No, I don't smoke",
    drinking: "Socially",
    exercise: "Often",
    pets: "I want pets",
    children: "I am open to kids",
    willRelocateForMarriage: "Maybe",
    communicationStyle: "Direct",
    loveLanguage: "Quality Time",
    financialStyle: "Balanced",
    location: { type: "Point", coordinates: [-0.187, 5.6037], city: "Accra", state: "Greater Accra", country: "Ghana" },
    questions: [
      { question: "My hidden talent is…", answer: "I can mix a DJ set while debugging JavaScript. True story." },
      { question: "The way to my heart is…", answer: "Good jollof, good music, and someone who actually texts back 😂" },
    ],
  },
];

// ── Matches — pairs of profile indices (0-based) that should be matched ──
const matchPairs = [
  [0, 1],   // Adaeze ↔ Chidi
  [0, 5],   // Adaeze ↔ Obinna
  [2, 9],   // Amina ↔ Tunde
  [2, 11],  // Amina ↔ Sekou
  [3, 4],   // Kwame ↔ Fatou
  [3, 8],   // Kwame ↔ Nia
  [6, 13],  // Zanele ↔ Daniel
  [7, 10],  // Emeka ↔ Chiamaka
  [12, 17], // Aisha ↔ Ibrahim
  [15, 18], // Yaw ↔ Efua
  [16, 19], // Thandiwe ↔ Kofi (← cross-country match)
  [14, 5],  // Ngozi ↔ Obinna
];

// ── Seed function ────────────────────────────────────────────────────────────
const seedProfiles = async () => {
  await connectDB();

  console.log("\n🗑️  Removing existing seed users...");
  const seedEmails = profiles.map((p) => p.email);
  await User.deleteMany({ email: { $in: seedEmails } });

  // Also clean up any old matches between seed users
  const hashedPassword = await bcrypt.hash(SHARED_PASSWORD, 10);

  console.log("👤 Creating 20 profiles...\n");
  const createdUsers = [];

  for (const profileData of profiles) {
    const { questions, ...userData } = profileData;

    const user = await User.create({
      ...userData,
      password: hashedPassword,
      isVerified: true,
      onboardingCompleted: true,
      onboardingStep: 99,
      verificationStatus: "approved",
      completionPercentage: 85 + Math.floor(Math.random() * 16), // 85-100%
      lastActive: new Date(),
      online: Math.random() > 0.5,
      images: pickPhotos(userData.gender),
      questions: questions || [],
      discoveryPreferences: {
        minAge: 18,
        maxAge: 40,
        maxDistance: 500,
        genderPreference: userData.gender === "Male" ? ["Female"] : ["Male"],
      },
      privacySettings: {
        profileVisibility: "everyone",
        showLastActive: true,
        showDistance: true,
        showAge: true,
        showOnlineStatus: true,
      },
    });

    createdUsers.push(user);
    console.log(`  ✅ ${user.firstName} ${user.lastName} (${user.gender}, ${user.age}) — ${user.location.city}, ${user.location.country}`);
  }

  // ── Create matches ─────────────────────────────────────────────────────────
  console.log("\n💕 Creating matches...\n");

  // Clean old matches between seed users
  const seedUserIds = createdUsers.map((u) => u._id);
  await Match.deleteMany({
    $or: [
      { user1: { $in: seedUserIds } },
      { user2: { $in: seedUserIds } },
    ],
  });

  for (const [i, j] of matchPairs) {
    const u1 = createdUsers[i];
    const u2 = createdUsers[j];

    // Ensure user1._id < user2._id for consistent compound index
    const [first, second] = u1._id.toString() < u2._id.toString() ? [u1, u2] : [u2, u1];

    await Match.create({
      user1: first._id,
      user2: second._id,
      status: "matched",
      initiatedBy: first._id,
      matchedAt: new Date(),
    });

    console.log(`  💕 ${u1.firstName} ↔ ${u2.firstName}`);
  }

  console.log(`\n🎉 Done! Created ${createdUsers.length} profiles and ${matchPairs.length} matches.`);
  console.log(`📧 All accounts use password: ${SHARED_PASSWORD}\n`);

  await mongoose.disconnect();
  process.exit(0);
};

seedProfiles().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
