import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  header: {
    backgroundColor: "#121212",
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: '#E5E5E5',
    marginBottom: 5,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#121212",
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
  },
  tab: {
    flex: 1,
    paddingVertical: 15,
    alignItems: "center",
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: "#3B82F6",
  },
  tabText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontWeight: "500",
  },
  activeTabText: {
    color: "#3B82F6",
  },
  listContainer: {
    padding: 15,
    paddingBottom: 20,
  },
  discoverCard: {
    backgroundColor: "#121212",
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  discoverHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  categoryIcon: {
    fontSize: 32,
    marginRight: 12,
  },
  categoryInfo: {
    flex: 1,
  },
  categoryName: {
    fontSize: 18,
    fontWeight: "600",
    color: '#E5E5E5',
    marginBottom: 4,
  },
  memberInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  categoryMembers: {
    fontSize: 14,
    color: '#9CA3AF',
    marginLeft: 4,
  },
  categoryDescription: {
    fontSize: 14,
    color: '#D1D5DB',
    lineHeight: 20,
    marginBottom: 10,
  },
  activityInfo: {
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#333333',
  },
  activityText: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  profilesHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#333333',
    backgroundColor: "#121212",
  },
  profilesTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: '#E5E5E5',
  },
  profilesList: {
    padding: 15,
  },
  profileCard: {
    backgroundColor: "#121212",
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    overflow: "hidden",
  },
  profileImage: {
    width: "100%",
    height: 300,
  },
  profileContent: {
    padding: 15,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  profileName: {
    fontSize: 20,
    fontWeight: "bold",
    color: '#E5E5E5',
    marginBottom: 4,
  },
  locationInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileDistance: {
    fontSize: 14,
    color: '#9CA3AF',
    marginLeft: 4,
  },
  profileOccupation: {
    fontSize: 16,
    color: "#3B82F6",
    fontWeight: "500",
    marginBottom: 8,
  },
  profileBio: {
    fontSize: 15,
    color: '#D1D5DB',
    lineHeight: 20,
    marginBottom: 12,
  },
  verifiedBadge: {
    backgroundColor: "#3B82F6",
    borderRadius: 10,
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  verifiedText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  interestsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 15,
  },
  interestPill: {
    backgroundColor: '#1E1E1E',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  interestText: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  moreInterestsPill: {
    backgroundColor: '#1E1A2E',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
  },
  moreInterestsText: {
    fontSize: 12,
    color: "#3B82F6",
    fontWeight: "600",
  },
  profileActions: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  passButton: {
    borderWidth: 1,
    borderColor: '#333333',
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 25,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    marginRight: 10,
  },
  passButtonText: {
    color: '#9CA3AF',
    fontWeight: "600",
  },
  likeButton: {
    backgroundColor: "#3B82F6",
    borderRadius: 25,
    paddingVertical: 10,
    paddingHorizontal: 25,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    flexDirection: "row",
  },
  likeButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    marginLeft: 5,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  noResultsContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  noResultsText: {
    fontSize: 18,
    fontWeight: "600",
    color: '#E5E5E5',
    marginBottom: 8,
    textAlign: "center",
  },
  noResultsSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: "center",
  },
});
